---
title: 'Discussion 11: Recommender Systems'
author: "John Ferrara"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Recommender Systems - X  (formerly Twitter)

### Directions
1) Perform a Scenario Design analysis as described below.  Consider whether it makes sense for your selected recommender system to perform scenario design twice, once for the organization (e.g. Amazon.com) and once for the organization's customers.

2) Attempt to reverse engineer what you can about the site, from the site interface and any available information that you can find on the Internet or elsewhere.

3) Include specific recommendations about how to improve the site's recommendation capabilities going forward. 

4) Create your report using an R Markdown file, and create a discussion thread with a link to the GitHub repo where your Markdown file notebook resides.  You are not expected to need to write code for this discussion assignment.


## 1 - Scenario Design Analysis

##### A) Who are your target users?
The target users for the platform X (formerly Twitter) range from casual everyday social media users, content producers, to those conducting research on specific issue areas (i.e., financial markets, geopolitics, etc.), engaging with the public from a brand-oriented perspecfic, and even journalists following breaking stories. The application has a very wide, generalized user base.

##### B) What are their goals?
The goals of the X platform seems to be inline with that of other content platforms. The company wants to encourage users to spend as much time on the platform as possible in order to maximize ad revenue, while also having users enjoy the experience. In recent years X has taken additional steps to help monetize the content on the platform via a premium subscription option with additional services, and offered to split revenue with those that produce viral content with a certain number of subscripbers.

##### C) How can you help them accomplish those goals?
In order to help the platform accomplish its goals, having the users volunatarily submit their usecase and intent upon sign up can help categorize users and customized their initial feed. As the users use the app more, the tags associated with the likes, retweets, follows, etc. should be considered in order to help weight new recommendations on the application. Over time, testing suggestions and identifying those suggestions that were successful at increasing user engagement and those that were not would be an ideal way to maximize these goals. 

## 2 - Reverse Engineer the Platform
The Twitter / X platform has two different modes for users. There is a feed that is based on a user's explicit follows, and then there is a "For You" feed that is a customized feed based on algorithms. According to the article cited below[^1], the way that the "For You" algorithm works is via four different stages: candidate sourcing, ranking, heurisitcs/filters, and Mixing/Serving. The overview of the process is that the algorithm takes abour 1,500 tweets that the user may see from followed accounts and other sources, then applies a rank to those tweets using metrics like engagement, recency and other factors. These ranked tweets are then moderated to ensure diverse sources from within and outside of the user's universe. Lastly, the tweets are mixed with ads and other content in order to provide the final product to the user. In fact, this process is actualy open-sourced by X itself[^2].


## 3 - Specific Recommendations
Some recommendations I would like to see implemented would be a user friendly transparency feature. This feature would allow users to manually edit or change the algorithm reccomendations via a specific portal where such ranks or associations with the accounts could be turned off, scalled up, or blunted. Being a social media user, such a portal would be useful for tweaking the content to my particular mood. For instance, if a user is seeing super poltical tweets and doesnt want to see them, although may regualrly like such content, the algorithm becomes a positive feedback loop. A user should be able to have a "reset" in content if so desired, and by toggling different tags, topic preferences, and other similar filters I think it would help users engage more. Rather than closing out of the application because of disatisfaction with the content. 


[^1]: Fourth Wall Blog, ["How Does the Twitter (X) Algorithm Work?"](https://fourthwall.com/blog/how-does-twitter-x-algorithm-work#:~:text=Twitter%20(X)'s%20open,data%20to%20generate%20tailored%20recommendations)

[^2]: Github "Twitter:the-algorithm"[Source](https://github.com/twitter/the-algorithm)